### ISSUE TITLE
Request for full code

### ISSUE THREAD

**Issue by Neo-Flash** [markusorsi/NPstereo#1]
Hello, thank you for sharing your work. Could I kindly request that you upload the complete code, including both the model and training code? Thank you very much.

**Comment by markusorsi** [comment]
Hi Neo, the GitHub repository contains the full code, but large files (like models) are missing due to size limits. You can regenerate these files directly from the code or download the complete repository, including trained models, from Zenodo. The link is in the README.

**Comment by Neo-Flash** [comment]
Hello, thank you for your reply. I was unable to find the model code (Python files) in the Zenodo NPstereo repository that you mentioned in your README. I only found the datasets used for training, validation, and testing. Could you kindly upload the complete NPstereo model code? I would like to train it myself to reproduce your results. Thank you!  @markusorsi

**Comment by markusorsi** [comment]
Hi Neo, thank you for clarifying, your request makes more sense to me now. For training the models, we are using the OpenNMT library, which provides all the necessary PyTorch classes and prebuilt models utilized in this repository. The specific model we are using is defined in the configuration files and constructed based on those specifications using the "onmt_train" command.

**Comment by Neo-Flash** [comment]
Got it! Thank you for pointing that out. I wasn’t aware of the OpenNMT library before, so I really appreciate your clarification. It’s good to know how the training process is set up and that the specific model configuration is managed through the OpenNMT library. This has been very insightful—thanks again! @markusorsi

**Comment by markusorsi** [comment]
You're welcome!
